### ISSUE TITLE
New methods

### ISSUE THREAD

**Issue by AndriiBilych** [p4ck493/ts-is#11]
It would be quite convenient to add is.zero and is.nan methods.

**Comment by Karbashevskyi** [comment]
is.nan makes no sense because the system has an isNaN method that allows you to check whether the value is not a number, in version 2.0.4 all these two methods were added, but in the new version 3.0.0 on the new-engine branch this method no longer exists, there is no many others, but our engine will use the environment where it is located in order to increase the number of available commands, via globalThis.
